/* 
	GroveGump.cs - Version 1.0

	Last Modified On 31/10/2003 at 20:38:03

	Script generated by Gump Creator 2.01
*/

using System;
using Server;
using Server.Gumps;
using Server.Network;

namespace Server.Gumps
{
	public class GroveGump : Gump
	{
		private Mobile m_Owner;
		public Mobile Owner{ get{ return m_Owner; } set{ m_Owner = value; } }

		public GroveGump(Mobile owner) : base( 10, 10 )
		{
			owner.CloseGump( typeof( GroveGump ) );

			int gumpX = 0; int gumpY = 0; //bool initialState = false;

			m_Owner = owner;

			Closable = true;
			Disposable = true;
			Dragable = true;
			Resizable = false;

			AddPage( 0 );

			gumpX = 0; gumpY = 0;
			AddImage( gumpX, gumpY, 0x9C4 );

			gumpX = 77; gumpY = 108;
			AddButton( gumpX, gumpY, 0x7D9, 0x7DA, 1, GumpButtonType.Reply, 0 );

			gumpX = 35; gumpY = 28;
			AddHtml( gumpX, gumpY, 148, 68, "If you fall asleep here, you feel sure you will be kept safe.", false, false );
		}

		public override void OnResponse( NetState state, RelayInfo info )
		{
			Mobile from = state.Mobile;

			switch( info.ButtonID )
			{
				case 1:
					break;
			}
		}
	}
}
